### ISSUE TITLE
Training code is incomplete

### ISSUE THREAD

**Issue by huang-CX** [nav74neet/ddpg_biped#2]

**Comment by huang-CX** [comment]
I have trained the agent for  48 hours, but it still can not walk stable. Can you tell me which part/hyper-parameter may result in this？

**Comment by navuboy** [comment]
Hey Huang, sorry for the late reply. Yes with ddpg, its quite common, that the training time will be excessively longer and the exploration will possibly never end. We tried different sets of hyperparameters for tuning the network, but unfornately it didnt work out. :(
