### ISSUE TITLE
Unable to Converge

### ISSUE THREAD

**Issue by Savanth123** [nav74neet/ddpg_biped#3]
Hi, 
I have been training  the robot for more than 40 hours still the robot is unable to learn. I mean i am unable to replicate results which you have got in the research paper. could you please share what hyper parameters you have been using to get results which published in your paper.

**Comment by ioarun** [comment]
Hey mate,
Sorry for this issue. The repository has not been maintained for a while now. Would revive it someday. Thanks for using it. Cheers!
